services:
  minecraft-server:
    build: .
    container_name: minecraft-bedrock-server
    ports:
      - "19132:19132/udp"  # Minecraft Bedrock server
      - "8000:8000/tcp"    # Management API
    volumes:
      # Main server config files
      - ./config/server.properties:/app/server.properties
      - ./config/allowlist.json:/app/allowlist.json
      - ./config/permissions.json:/app/permissions.json
      - ./valid_known_packs.json:/app/valid_known_packs.json
      
      # World data (persistent)
      - minecraft-worlds:/app/worlds

      # World-specific add-on configuration
      - ./world_configs/world_behavior_packs.json:/app/worlds/Bedrock level/world_behavior_packs.json
      - ./world_configs/world_resource_packs.json:/app/worlds/Bedrock level/world_resource_packs.json
      
      # Custom add-ons (staged for entrypoint script)
      - ./addons:/app/custom_addons
      
      # Logs (for external access)
      - ./logs:/app/logs
    environment:
      - SERVER_NAME=Bedrock Server
      - GAMEMODE=survival
      - DIFFICULTY=easy
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  minecraft-worlds:
    driver: local
